import { Match, Rally } from '@/types/table-tennis';

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match-1',
    date: '2026-08-20',
    matchType: 'official',
    tournamentName: '市民卓球選手権大会',
    opponentName: '佐藤 選手',
    opponentHand: 'right',
    opponentStyle: 'chopper',
    opponentRubberFore: 'inverted',
    opponentRubberBack: 'long_pips',
    gameFormat: 5,
    myScoreGames: 3,
    oppScoreGames: 1,
    isCompleted: true,
    notes: '相手はバック粒高のカットマン。ツッツキで粘りつつチャンスボールをミドルへドライブしたのが効果的だった。',
    createdAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'match-2',
    date: '2026-08-25',
    matchType: 'practice',
    tournamentName: 'クラブ内リーグ戦',
    opponentName: '鈴木 選手',
    opponentHand: 'left',
    opponentStyle: 'shake_attack',
    opponentRubberFore: 'inverted',
    opponentRubberBack: 'inverted',
    gameFormat: 5,
    myScoreGames: 2,
    oppScoreGames: 3,
    isCompleted: true,
    notes: 'サウスポー相手。フォア前ショートサーブからの展開で優位に立てたが、バックハンドのミスが多かった。',
    createdAt: '2026-08-25T14:30:00.000Z',
  },
  {
    id: 'match-3',
    date: '2026-08-28',
    matchType: 'unofficial',
    tournamentName: 'オープン交流練習会',
    opponentName: '田中 選手',
    opponentHand: 'right',
    opponentStyle: 'pips_attack',
    opponentRubberFore: 'short_pips',
    opponentRubberBack: 'inverted',
    gameFormat: 3,
    myScoreGames: 2,
    oppScoreGames: 0,
    isCompleted: true,
    notes: '前陣速攻型の選手。サーブの長短で崩してブロックをかわした。',
    createdAt: '2026-08-28T16:00:00.000Z',
  }
];

export const INITIAL_RALLIES: Rally[] = [
  // Match 1 (対カットマン)
  {
    id: 'rally-101',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 0,
    scoreOpp: 0,
    result: 'won',
    server: 'self',
    actionCategory: 'serve',
    serveLength: 'short',
    serveCourse: 'fore',
    serveSpin: 'backspin',
    createdAt: '2026-08-20T10:01:00.000Z',
  },
  {
    id: 'rally-102',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 1,
    scoreOpp: 0,
    result: 'won',
    server: 'self',
    actionCategory: 'third_ball',
    serveLength: 'short',
    serveCourse: 'back',
    serveSpin: 'side_back',
    thirdBallHand: 'forehand',
    thirdBallReceiveCourse: 'middle',
    thirdBallTargetCourse: 'middle',
    thirdBallType: 'loop_drive',
    createdAt: '2026-08-20T10:02:00.000Z',
  },
  {
    id: 'rally-103',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 2,
    scoreOpp: 0,
    result: 'lost',
    server: 'opponent',
    actionCategory: 'receive',
    receiveTechnique: 'push',
    receiveCourse: 'back',
    missType: 'net',
    createdAt: '2026-08-20T10:03:00.000Z',
  },
  {
    id: 'rally-104',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 2,
    scoreOpp: 1,
    result: 'won',
    server: 'opponent',
    actionCategory: 'receive',
    receiveTechnique: 'push',
    receiveCourse: 'fore',
    createdAt: '2026-08-20T10:04:00.000Z',
  },
  {
    id: 'rally-105',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 3,
    scoreOpp: 1,
    result: 'won',
    server: 'self',
    actionCategory: 'rally',
    rallyType: 'chance_ball',
    createdAt: '2026-08-20T10:05:00.000Z',
  },
  {
    id: 'rally-106',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 4,
    scoreOpp: 1,
    result: 'lost',
    server: 'self',
    actionCategory: 'third_ball',
    thirdBallHand: 'forehand',
    thirdBallReceiveCourse: 'back',
    thirdBallTargetCourse: 'fore',
    thirdBallType: 'drive',
    missType: 'net',
    createdAt: '2026-08-20T10:06:00.000Z',
  },
  {
    id: 'rally-107',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 4,
    scoreOpp: 2,
    result: 'won',
    server: 'opponent',
    actionCategory: 'receive',
    receiveTechnique: 'stop',
    receiveCourse: 'fore',
    createdAt: '2026-08-20T10:07:00.000Z',
  },
  {
    id: 'rally-108',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 5,
    scoreOpp: 2,
    result: 'lost',
    server: 'opponent',
    actionCategory: 'rally',
    rallyType: 'connect',
    missType: 'over',
    createdAt: '2026-08-20T10:08:00.000Z',
  },
  {
    id: 'rally-109',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 5,
    scoreOpp: 3,
    result: 'won',
    server: 'self',
    actionCategory: 'serve',
    serveLength: 'short',
    serveCourse: 'fore',
    serveSpin: 'reverse_side_back',
    createdAt: '2026-08-20T10:09:00.000Z',
  },
  {
    id: 'rally-110',
    matchId: 'match-1',
    gameNumber: 1,
    scoreMy: 6,
    scoreOpp: 3,
    result: 'lost',
    server: 'self',
    actionCategory: 'serve_miss',
    serveLength: 'long',
    serveCourse: 'back',
    serveSpin: 'side_top',
    createdAt: '2026-08-20T10:10:00.000Z',
  },

  // Match 2 (対サウスポー・シェーク攻撃)
  {
    id: 'rally-201',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 0,
    scoreOpp: 0,
    result: 'won',
    server: 'self',
    actionCategory: 'serve',
    serveLength: 'short',
    serveCourse: 'fore',
    serveSpin: 'backspin',
    createdAt: '2026-08-25T14:31:00.000Z',
  },
  {
    id: 'rally-202',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 1,
    scoreOpp: 0,
    result: 'lost',
    server: 'self',
    actionCategory: 'third_ball',
    thirdBallHand: 'backhand',
    thirdBallReceiveCourse: 'back',
    thirdBallTargetCourse: 'back',
    thirdBallType: 'drive',
    missType: 'net',
    createdAt: '2026-08-25T14:32:00.000Z',
  },
  {
    id: 'rally-203',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 1,
    scoreOpp: 1,
    result: 'won',
    server: 'opponent',
    actionCategory: 'receive',
    receiveTechnique: 'chiquita',
    receiveCourse: 'fore',
    createdAt: '2026-08-25T14:33:00.000Z',
  },
  {
    id: 'rally-204',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 2,
    scoreOpp: 1,
    result: 'lost',
    server: 'opponent',
    actionCategory: 'receive',
    receiveTechnique: 'flick',
    receiveCourse: 'middle',
    missType: 'over',
    createdAt: '2026-08-25T14:34:00.000Z',
  },
  {
    id: 'rally-205',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 2,
    scoreOpp: 2,
    result: 'won',
    server: 'self',
    actionCategory: 'third_ball',
    thirdBallHand: 'forehand',
    thirdBallReceiveCourse: 'middle',
    thirdBallTargetCourse: 'back',
    thirdBallType: 'drive',
    createdAt: '2026-08-25T14:35:00.000Z',
  },
  {
    id: 'rally-206',
    matchId: 'match-2',
    gameNumber: 1,
    scoreMy: 3,
    scoreOpp: 2,
    result: 'lost',
    server: 'self',
    actionCategory: 'rally',
    rallyType: 'block',
    missType: 'net_in', // 相手ネットイン
    createdAt: '2026-08-25T14:36:00.000Z',
  }
];
